### ISSUE TITLE
html vs json responses

### ISSUE THREAD

**Issue by bongolegend** [paper-dragonfly/ttt_web#2]
https://github.com/paper-dragonfly/ttt_web/blob/d2d68188c34a4d795be5bcb9b0bc6ff0ab0e0f17/ttt_web/ttt_app.py#L22

so really, you didn't create a correct api from a curl standpoint. when someone interacts with your api, they pass in json, and they expect to receive json. This allows them to parse the json to get the data they need. In this example, you should respond with json that looks like this:
```
{
    "message": "game created successfully.",
    "game_id": 2
} 
```

**Comment by paper-dragonfly** [comment]
ok
