### ISSUE TITLE
weird choice of variable name

### ISSUE THREAD

**Issue by bongolegend** [paper-dragonfly/ttt_web#4]
https://github.com/paper-dragonfly/ttt_web/blob/d2d68188c34a4d795be5bcb9b0bc6ff0ab0e0f17/ttt_web/ttt_app.py#L48

It is more common to use active verbs as function names, not as variable names for objects.

**Comment by paper-dragonfly** [comment]
changed it to var name: player_symbol with a single return item str rather than Tuple[bool, str, str]
