### ISSUE TITLE
switch to dict

### ISSUE THREAD

**Issue by bongolegend** [paper-dragonfly/ttt_web#5]
https://github.com/paper-dragonfly/ttt_web/blob/d2d68188c34a4d795be5bcb9b0bc6ff0ab0e0f17/ttt_web/ttt_app.py#L51

when you have more than 2 values in a tuple, it's better to use a dict, that way you don't need to remember which position corresponds to which value.

**Comment by paper-dragonfly** [comment]
good thought, though I solved this by changing what update_move_log returns
