### ISSUE TITLE
use try finally for closing connection

### ISSUE THREAD

**Issue by bongolegend** [paper-dragonfly/ttt_web#6]
https://github.com/paper-dragonfly/ttt_web/blob/d2d68188c34a4d795be5bcb9b0bc6ff0ab0e0f17/ttt_web/ttt_app.py#L60-L61

the way you should do your connection and cursor is like this, so that if there is an error, the connection still gets closed.
```
try:
    conn, cur = create()
    do_thing()
    do_another_thing_that_fails()
finally:
    cur.close()
    conn.close()
```

**Comment by paper-dragonfly** [comment]
ok I did it for all my connections
