### ISSUE TITLE
combine these into a one liner. that's the convention everyone else follows

### ISSUE THREAD

**Issue by bongolegend** [paper-dragonfly/ttt_web#7]
https://github.com/paper-dragonfly/ttt_web/blob/d2d68188c34a4d795be5bcb9b0bc6ff0ab0e0f17/ttt_web/ttt_app.py#L82-L83

**Comment by paper-dragonfly** [comment]
I'm not sure how to. I tried playing around with it but keep getting errors: 
game_names = cur.execute(sql,str_subs).fetchall() -> AttributeError: 'NoneType' object has no attribute 'fetchall'
game_names = cur.fetchall(execute(sql,str_subs)) -> TypeError: cursor.fetchall() takes no arguments (1 given)

**Comment by bongolegend** [comment]
oh good point. nvm.
