### ISSUE TITLE
you didn't specify the methods accepted.

### ISSUE THREAD

**Issue by bongolegend** [paper-dragonfly/ttt_web#8]
https://github.com/paper-dragonfly/ttt_web/blob/d2d68188c34a4d795be5bcb9b0bc6ff0ab0e0f17/ttt_web/ttt_app.py#L92

**Comment by paper-dragonfly** [comment]
that's because it only takes 'GET' and methods=["GET"] is the default

**Comment by paper-dragonfly** [comment]
but I changed it anyway to be explicit
